version: '3'
services:
  rush-hour:
    build: ./rush-hour
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka
  worker:
    build: ./worker
    depends_on:
      - kafka
  cronjob:
    build: ./cronjob
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RushHour
    ports:
      - "5432:5432"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
